---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
library(ape)
library(phyloseq)
library(tidyverse)
library(writexl)
library(vegan)
library(microbiome)
library(ggpubr)
library(ggpubr)
library(alluvial)
library(ggalluvial)

setwd("~/OneDrive/University of Helsinki/msc_thesis/bact_comm")
```



```{r}
physeqR <- readRDS("PhySeq_BrakenHumGut_05.07.22.rds")


Pal6 <- c("#BB3E03", "#E9C46A", "#CA6702", "#0A9396",
          "#005F73", "#80BBA8")

Pal10 <- c("#9B2226","#AE2012", "#BB3E03", "#CA6702", "#EE9B00", "#E9C46A",
           "#80BBA8", "#0A9396", "#005F73", "#033549")

ClustersB4.5 <- c("#005F73","#0A9396", "#80BBA8")
ClustersB7.9 <- c("#BB3E03","#EE9B00")

Clusters <- c("#005F73","#0A9396", "#80BBA8","#BB3E03","#EE9B00")
```



# Cluster data merging
```{r}

B4 <- read_csv("HClust_F_CLR_B4.5_18.08.22.csv") %>% 
  mutate(Cluster=paste("EC", ClusterID, sep="_")) 
B7 <- read_csv("HClust_F_CLR_B7.9_18.08.22.csv") %>% rowwise() %>%
  mutate(Cluster=paste("LC", ClusterID, sep="_")) 

all_TP <- B4 %>% add_row(B7)

cluster_table <- all_TP %>% separate(Sample_ID, into=c("Family_ID", "Sample_type"), sep="_", remove=FALSE)


# get info Cluster in PhySeq object
sam.new <- cluster_table %>% select(Sample_ID, Cluster)
sam.new <- sam.new %>% column_to_rownames(var="Sample_ID")

# Add new FCT in metadata 
sam.new <- sample_data(sam.new)
physeqR_data <- merge_phyloseq(physeqR, sam.new)

# add birthmode in Cluster table
sam.old <- sample_data(physeqR) %>%
    data.frame() %>% rownames_to_column(var="Sample_ID") 

cluster_table <- left_join(cluster_table, sam.old)

#write_csv(cluster_table, "recap_clusters.csv")
```

# alluvial plots 
```{r}
time_point_labels <- c("3 months", "6 months", "12 months", "24 months")
names(time_point_labels) <- c("B4", "B5", "B7", "B9")


cluster_table$FCT <- as.factor(cluster_table$Cluster)

ggplot(cluster_table,
       aes(x = Sample_type, stratum = Cluster, alluvium = Family_ID,
           fill = Cluster)) +
  geom_flow() +
  geom_stratum() +
  theme(legend.position = "bottom") +
  labs(y="Number of infants", x="time points")+
  scale_x_discrete(labels=time_point_labels)+
  theme(axis.text.x = element_text(angle = 50, hjust = 0.9, size = 10)) +
  theme_bw() +
  scale_fill_manual(values=Clusters)


#ggsave("Figure3A.pdf", width = 24, height = 15, units = "cm", limitsize = F)
```

# Composition
```{r}

# composition plots
physeqR_data_compo_T  <- microbiome::transform(physeqR_data, "compositional") %>%
  subset_samples(Sample_type %in% c("B4","B5","B7", "B9"))
psG  <- aggregate_rare(physeqR_data_compo_T, level="family", detection=0.1, prevalence=0.1) 

plot_data <- psmelt(psG) %>% select(Sample, Sample_type, OTU, Abundance, Cluster)

plot_data_av <- plot_data %>% group_by(OTU, Sample_type, Cluster) %>% 
  mutate(av_Abundance=mean(Abundance)) %>%
  select(OTU, Sample_type, Cluster, av_Abundance) %>% unique()

plot_data_av %>%  ggplot(aes(fill=OTU, y=av_Abundance, x=Cluster)) + 
    geom_bar(position="stack", stat="identity") +
  facet_grid(.~Sample_type, scales = "free_x")+
  theme_bw()
  


#ggsave("Figure3B.pdf", width = 24, height = 15, units = "cm", limitsize = F)
```

# permanova

```{r}

#B4 
physeq.gen <- aggregate_taxa(physeqR_data, level = "family")
physeq.gen <- subset_samples(physeq.gen, Sample_type=="B4")
physeq.genrel<- microbiome::transform(physeq.gen, "clr")

otu <- abundances(physeq.genrel)
meta <- meta(physeq.genrel)

permanova <- adonis(t(otu) ~ Cluster,
               data = meta, permutations=9999, method = "euclidean")

# P-value
print(as.data.frame(permanova$aov.tab)["Cluster", "Pr(>F)"])
```


```{r}
#B5
physeq.gen <- aggregate_taxa(physeqR_data, level = "family")
physeq.gen <- subset_samples(physeq.gen, Sample_type=="B5")
physeq.genrel<- microbiome::transform(physeq.gen, "clr")

otu <- abundances(physeq.genrel)
meta <- meta(physeq.genrel)

permanova <- adonis(t(otu) ~ Cluster,
               data = meta, permutations=9999, method = "euclidean")

# P-value
print(as.data.frame(permanova$aov.tab)["Cluster", "Pr(>F)"])
```

```{r}
#B7
physeq.gen <- aggregate_taxa(physeqR_data, level = "family")
physeq.gen <- subset_samples(physeq.gen, Sample_type=="B7")
physeq.genrel<- microbiome::transform(physeq.gen, "clr")

otu <- abundances(physeq.genrel)
meta <- meta(physeq.genrel)

permanova <- adonis(t(otu) ~ Cluster,
               data = meta, permutations=9999, method = "euclidean")

# P-value
print(as.data.frame(permanova$aov.tab)["Cluster", "Pr(>F)"])
```


```{r}
#B9
physeq.gen <- aggregate_taxa(physeqR_data, level = "family")
physeq.gen <- subset_samples(physeq.gen, Sample_type=="B9")
physeq.genrel<- microbiome::transform(physeq.gen, "clr")

otu <- abundances(physeq.genrel)
meta <- meta(physeq.genrel)

permanova <- adonis(t(otu) ~ Cluster,
               data = meta, permutations=9999, method = "euclidean")

# P-value
print(as.data.frame(permanova$aov.tab)["Cluster", "Pr(>F)"])
```


